App-1342-Incorrect status code on Integration Bridge Authorization API
SymphonyOSF/App-Integrations-Jira pull request #103
Opened 2017-10-17 11:57 UTC by Hamitay-Daitan

Added status code on JiraOAuth1Exception and changed exception handling on JiraWebHookIntegration

2017-10-17 15:33 UTC, campidelli requested changes

2017-10-17 15:33 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/jira/webhook/JiraWebHookIntegration.java
> +          HttpStatus.BAD_REQUEST.value(), MSG.getMessage(MSG_INSUFFICIENT_PARAMS_SOLUTION));
I don't think we should handle HTTP codes in this layer. This layer should be independent of protocols. It's better to extend JiraOAuth1Exception and create a meaningful Exception to express what you want here.

2017-10-17 15:33 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/jira/authorization/oauth/v1/JiraOAuth1Exception.java
> +  public JiraOAuth1Exception(String message, int code,
Http code here? I prefer to use them only in the RemoteApiException.

2017-10-17 15:33 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/jira/webhook/JiraWebHookIntegration.java
> +          HttpStatus.NOT_FOUND.value(), MSG.getMessage(MSG_NO_INTEGRATION_FOUND_SOLUTION));
Same comment as above.

2017-10-18 12:56 UTC, robson-sanchez requested changes

2017-10-18 12:56 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/oauth/v1/exception/JiraOAuth1IntegrationNotFoundException.java
> +public class JiraOAuth1IntegrationNotFoundException extends OAuth1IntegrationNotFoundException {
I think this class is not useful for a while. Please remove this one.

2017-10-18 12:56 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/oauth/v1/exception/JiraOAuth1MissingParametersException.java
> +public class JiraOAuth1MissingParametersException extends OAuth1MissingParametersException {
Same comment above.

2017-10-18 12:56 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/webhook/JiraWebHookIntegration.java
> +      throw new JiraOAuth1MissingParametersException(MSG.getMessage(MSG_INSUFFICIENT_PARAMS),
You should throw OAuth1MissingParametersException directly.

2017-10-18 12:56 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/webhook/JiraWebHookIntegration.java
> +      throw new JiraOAuth1IntegrationNotFoundException(MSG.getMessage(MSG_NO_INTEGRATION_FOUND),
You should throw OAuth1IntegrationNotFoundException directly.

2017-10-18 15:02 UTC, robson-sanchez approved these changes

2017-10-18 18:10 UTC, merged