APP-751 fixing line-breaks on presentation and entity fields
SymphonyOSF/App-Integrations-Jira pull request #20
Opened 2017-03-22 11:47 UTC by ecarrenho-daitan

Adding test cases for line-breaks.

2017-03-23 18:20 UTC, robson-sanchez requested changes

2017-03-23 18:20 UTC, rsanchez-daitan commented on src/test/resources/parser/commentJiraParser/commentAddedWithLinebreakMessageML.xml
> +<entity type="com.symphony.integration.jira.event.issue_commented" version="1.0"><presentationML>Test User commented on Story SAM-25, Issue Test (<a href="https://whiteam1.atlassian.net/browse/SAM-25
Could you format this XML?

2017-03-23 21:46 UTC, ecarrenho-daitan commented on src/test/resources/parser/commentJiraParser/commentAddedWithLinebreakMessageML.xml
> +<entity type="com.symphony.integration.jira.event.issue_commented" version="1.0"><presentationML>Test User commented on Story SAM-25, Issue Test (<a href="https://whiteam1.atlassian.net/browse/SAM-25
Done.

2017-03-24 16:08 UTC, robson-sanchez approved these changes

2017-03-24 16:24 UTC, merged