APP-1179/APP-1180 : IB APIs to search for Jira users / assign new ticket to user
SymphonyOSF/App-Integrations-Jira pull request #73
Opened 2017-08-16 12:21 UTC by Hamitay-Daitan

2017-08-16 14:10 UTC, robson-sanchez requested changes

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +@RequestMapping("/v1/{configurationId}/rest/api")
Please change it to: "@RequestMapping("/v1/jira/rest/api")"

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private final IntegrationBridge integrationBridge;
I think it won't required anymore. Change this attribute to JiraWebHookIntegration class and fix the constructor injection.

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private final Integer maxResults = new Integer(10);
Hardcoded is not a good solution. We should modify it to a parameterized value on the YAML config file and keep the 10 value as a fallback.

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private String accessToken;
It's used on the method scope, it's not required to be an attribute.

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * Get a list of potential assigneers users from an especific Issue.
Get a list of potential assignable users from a specific issue.

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * @param username User that made a request from JIRA
The username you want to query from JIRA

2017-08-16 14:10 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * @return List of potential assigneers users or 400 Bad Request - Returned if no issue key
@return List of potential assignable users or 
   400 Bad Request - Returned if no issue key was provided or invalid
   401 Unauthorized - Returned if the user is not authenticated

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +      throws IOException {
Why IOException?

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +    AuthorizedIntegration authIntegration = getAuthorizedIntegration(configurationId);
Change this to: validateIntegrationBootstrap(jiraWebHookIntegration)

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private String getAccessToken(
Once this method has only one line I think it's not required

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResourceConstants.java
> +  public static String ISSUE_KEY = "issueKey";
It should be 'public static final'.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResourceConstants.java
> +public class JiraApiResourceConstants {
Missing javadoc.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResourceExceptionHandler.java
> +public class JiraApiResourceExceptionHandler {
Missing javadoc.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
> +      throws AuthorizationException, OAuth1HttpRequestException {
The OAuth1HttpRequestException exception won't be required anymore.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/properties/ServiceProperties.java
> +public class ServiceProperties {
Missing javadoc.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +public class SearchAssignableUsersService {
Missing javadoc.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/webhook/JiraWebHookIntegration.java
> +      throws AuthorizationException, OAuth1HttpRequestException {
The OAuth1HttpRequestException exception won't be required anymore.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManagerTest.java
> +      throws AuthorizationException, URISyntaxException, OAuth1HttpRequestException {
The OAuth1HttpRequestException exception won't be required anymore.

2017-08-16 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManagerTest.java
> +      throws AuthorizationException, OAuth1HttpRequestException {
The OAuth1HttpRequestException exception won't be required anymore.

2017-08-16 15:48 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +@RequestMapping("/v1/{configurationId}/rest/api")
Done!
96199b287619b90657d6a5d4dee3224a1687b0fa

2017-08-16 16:32 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private final IntegrationBridge integrationBridge;
Done!
79afb405f3a718c7cd037b56b3272b0c114a121a

2017-08-16 17:00 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private String accessToken;
Done!
bc49f6e6bff398a7228c359488e73dc0097fd02d

2017-08-16 17:09 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +    AuthorizedIntegration authIntegration = getAuthorizedIntegration(configurationId);
Done!
ca72590eb57fcd9832505185cf7a216795e3e6e8

2017-08-16 17:11 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * Get a list of potential assigneers users from an especific Issue.
Done!
4cba9bee7500073e2f257b78ec47e1e799d93799

2017-08-16 17:12 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * @param username User that made a request from JIRA
Done!
cc98bf40c021f47559baa6eac98aee5cb871e6fd

2017-08-16 17:24 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
> +      throws AuthorizationException, OAuth1HttpRequestException {
Done!
7bd958140d410badc01e5a63ebf9e42161ff0d52

2017-08-16 17:25 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/webhook/JiraWebHookIntegration.java
> +      throws AuthorizationException, OAuth1HttpRequestException {
Done!
7bd958140d410badc01e5a63ebf9e42161ff0d52

2017-08-16 17:44 UTC, ardsilva commented on src/test/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManagerTest.java
> +      throws AuthorizationException, URISyntaxException, OAuth1HttpRequestException {
Done!
5f99cea017dec4bc48b3bc64022713e42f648a7b

2017-08-16 17:44 UTC, ardsilva commented on src/test/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManagerTest.java
> +      throws AuthorizationException, OAuth1HttpRequestException {
Done!
5f99cea017dec4bc48b3bc64022713e42f648a7b

2017-08-16 18:20 UTC, robson-sanchez requested changes

2017-08-16 18:20 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
>      AppAuthorizationModel appAuthorizationModel = getAuthorizationModel(settings);
We are reading public/private key on the filesystem on every request. It's a lot of unnecessary I/O operations.

2017-08-16 18:20 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/exception/InvalidJiraURLException.java
> +public class InvalidJiraURLException extends RuntimeException {
Missing javadoc. All unchecked exceptions must extend IntegrationRuntimeException

2017-08-16 18:31 UTC, robson-sanchez requested changes

2017-08-16 18:31 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +  public ResponseEntity searchAssingablesUsers(String accessToken, OAuth1Provider provider,
Missing javadoc.

You don't need to pass component as a parameter, this a constant. You could define it as a constant field in a separate class that holds the constant fields.

2017-08-16 18:31 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
Missing the message how to fix it.

2017-08-16 18:31 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      URL myselfUrl, String component, String issueKey) throws IOException {
IOException?

2017-08-16 18:31 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      URL myselfUrl, String component, String issueKey) throws IOException {
Change 'myselfUrl' to 'assignableUserUrl'.

2017-08-16 18:31 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      response = provider.makeAuthorizedRequest(accessToken, myselfUrl, HttpMethods.GET, null);
You should change to:

```
HttpResponse response = provider.makeAuthorizedRequest(accessToken, myselfUrl, HttpMethods.GET, null);
return ResponseEntity.ok().body(response.parseAsString());
```

2017-08-16 18:31 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +        errorResponse.setMessage(e.getLocalizedMessage());
Are you sure that's the real message you should answer to the user?

2017-08-16 18:58 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      URL myselfUrl, String component, String issueKey) throws IOException {
Done!
801056d13c2165b996f1b73df969ffd789ec4d60

2017-08-16 19:17 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResourceConstants.java
> +public class JiraApiResourceConstants {
Done!
f823bbfe5f1edafa89a71daaa18090b37aa6b81e

2017-08-16 19:28 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResourceConstants.java
> +  public static String ISSUE_KEY = "issueKey";
Done!
c36918cbf64c4fe9b07ae0cb629ebd7b55c6f492

2017-08-16 19:47 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResourceExceptionHandler.java
> +public class JiraApiResourceExceptionHandler {
done!
23e54a93288f8c88f745c5727c6328446f7f39c5

2017-08-16 19:54 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/properties/ServiceProperties.java
> +public class ServiceProperties {
done!
f3300cb5c1e9b5174216735c79b00e3418dc140a

2017-08-16 19:57 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +public class SearchAssignableUsersService {
Done!
e872e578747710504dc6c3d6fe4f7e039fd199a6

2017-08-16 20:29 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +  public ResponseEntity searchAssingablesUsers(String accessToken, OAuth1Provider provider,
Done!
acb124f0616c1359cfa66cee37778a54a77c6aec

2017-08-16 20:31 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      URL myselfUrl, String component, String issueKey) throws IOException {
done!
c1aecfc649b75febca9d3a17f2736e6d6313c0b8

2017-08-16 20:33 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
done!
49815acdde0fe1714adada8aacf57f325d3686ad

2017-08-17 14:14 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      response = provider.makeAuthorizedRequest(accessToken, myselfUrl, HttpMethods.GET, null);
done!
c4e55be16c602e4e7200b278f0be298999c09c43

2017-08-17 14:14 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +        errorResponse.setMessage(e.getLocalizedMessage());
done!
c4e55be16c602e4e7200b278f0be298999c09c43

2017-08-17 16:13 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +  public ResponseEntity searchAssingablesUsers(String accessToken, OAuth1Provider provider,
3f3a27738ac03f7dbe8f50e4aee047270c60076d

2017-08-18 12:55 UTC, robson-sanchez requested changes

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
> +          e, logMessage.getMessage("integration.jira.url.api.invalid.solution"));
Change this message to: integration.jira.unreachable

integration.jira.unreachable = "Cannot access JIRA instance"
integration.jira.unreachable.solution = "Make sure the JIRA instance {0} is working fine"

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
> +  public String getAccessToken(IntegrationSettings settings, String url, Long userId)
Missing javadoc

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
> +  private JiraOAuth1Data getJiraOAuth1Data(UserAuthorizationData userAuthorizationData)
Missing javadoc

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
> +  public UserAuthorizationData getUserAuthorizationData(IntegrationSettings settings, String url,
Missing javadoc

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +    if (StringUtils.isEmpty(issueKey)) {
Duplicated code. Throws a common exception and deal with this on the exception handler.

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      if (e.getCode() == HttpStatus.NOT_FOUND.value()) {
Duplicated code. Throws a common exception and deal with this on the exception handler.

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +  private LogMessageSource logMessage;
Change the LogMessageSource to MessageUtils.

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/UserAssignService.java
> +    if (StringUtils.isEmpty(issueKey)) {
Duplicated code. Throws a common exception and deal with this on the exception handler.

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/UserAssignService.java
> +  public ResponseEntity assignUserToIssue(String accessToken, String issueKey, String username,
Missing javadoc

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/UserAssignService.java
> +      if (e.getCode() == HttpStatus.NOT_FOUND.value()) {
Duplicated code. Throws a common exception and deal with this on the exception handler.

2017-08-18 12:55 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/UserAssignService.java
> +      if (e.getCode() == HttpStatus.BAD_REQUEST.value()) {
Throws a common exception and deal with this on the exception handler.

2017-08-18 14:32 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/SearchAssignableUsersService.java
> +      if (e.getCode() == HttpStatus.NOT_FOUND.value()) {
DONE

2017-08-21 13:42 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/authorization/JiraAuthorizationManager.java
>      AppAuthorizationModel appAuthorizationModel = getAuthorizationModel(settings);
DONE

2017-08-21 17:00 UTC, robson-sanchez approved these changes

2017-08-21 17:00 UTC, merged