APP-1248: Create an integration bridge API for commenting on JIRA
SymphonyOSF/App-Integrations-Jira pull request #76
Opened 2017-08-22 19:00 UTC by ardsilva

2017-08-22 20:08 UTC, robson-sanchez requested changes

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * @return 201 Created - Returned if add was successful or 400 Bad Request - Returned if the input
You are returning 200 instead of 201. Please fix the documentation.

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private static final String PATH_JIRA_API_COMMENT_ISSUE =
I think the service component should deal with the JIRA paths. Please move this constant to the service component.

The same comment is valid to other services.

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/exception/BodyContentNotFoundException.java
> +public class BodyContentNotFoundException extends IntegrationRuntimeException {
You might rename this class to 'MissingRequiredPayloadException'.

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/exception/BodyContentNotFoundException.java
> + * Unchecked exception thrown to indicate the body path content was not found.
Unchecked exception to reports the lack of request payload.

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +    validateComment(comment);
You should encapsulate the logic to retrieve comment inside a method.

This method might validate the input and deal with JSON unmarshalling.

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +      malformedCommentExcpetion();
You should create and throw another exception like 'InvalidJiraPayloadException'.

2017-08-22 20:08 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +    validateComment(body);
This validation should be inside the service component. You should throw another exception like 'InvalidJiraCommentException'.

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/properties/JiraErrorMessageKeys.java
> +  public static final String APPLICATION_KEY_ERROR = "integration.jira.private.key.validation";
good catch :clap:

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/IssueCommentService.java
> +  public ResponseEntity addCommentToAnIssue(String accessToken, String issueKey,
Missing javadoc.

Btw, it seems a weird style formatting.

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/IssueCommentService.java
> +    validateIssueKeyParameter(issueKey);
You should validate the comment body as well.

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/jira/services/IssueCommentService.java
> +      throw new JiraUnexpectedException(SERVICE_NAME, e.getMessage(), e);
You should validate the bad request as well.

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/jira/exception/BodyContentNotFoundExceptionTest.java
> +import static org.junit.Assert.*;
Avoid wildcards.

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/jira/exception/JiraUnexpectedExceptionTest.java
>  import static org.junit.Assert.*;
Avoid wildcards

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/jira/exception/IssueKeyNotFoundExceptionTest.java
>  import static org.junit.Assert.*;
Avoid wildcards.

2017-08-22 20:08 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/jira/exception/InvalidJiraURLExceptionTest.java
>  import static org.junit.Assert.*;
Avoid wildcards.

2017-08-22 20:20 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +  private static final String PATH_JIRA_API_COMMENT_ISSUE =
done!

2017-08-23 11:50 UTC, ardsilva commented on src/main/java/org/symphonyoss/integration/jira/api/JiraApiResource.java
> +   * @return 201 Created - Returned if add was successful or 400 Bad Request - Returned if the input
b6e6729a3359de044768930b368cb48b9790a444

2017-08-24 12:47 UTC, robson-sanchez approved these changes

2017-08-24 12:47 UTC, merged